apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: webDummy
  namespace: cmp
spec:
  selector:
    matchLabels:
      app: webDummy
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: webDummy
    spec:
      containers:
      - name: webDummy
        image: registry.tools.adidas-group.com/cmp/dummyWeb:test
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.1
            memory: 64Mi
          limits:
            cpu: 0.5
            memory: 128Mi
        livenessProbe:
            httpGet:
              path: /
              port: 80