---
apiVersion: v1
kind: Service
metadata:
  name: webDummy
  namespace: cmp
  labels:
    app: webDummy
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: webDummy
  selector:
    app: webDummy